- name: Install dankshell packages
  become: true
  community.general.pacman:
    name:
      - dgop # Dank GO Process Status
      - cava # Audio visualizer
    state: present
- name: Install AUR packages for dankshell
  ansible.builtin.include_role:
    name: aur_build
  vars:
    aur_packages:
      - dms-shell-bin
      - dsearch-bin # dank search
