- name: Install font packages
  become: true
  community.general.pacman:
    name:
      - fontconfig
      - ttf-jetbrains-mono-nerd
      - ttf-dejavu
      - ttf-nerd-fonts-symbols
      - ttf-ubuntu-font-family
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
      - ttf-liberation
      - unzip
      - wget
      - curl
      - ttf-cascadia-code-nerd
      - ttf-cascadia-mono-nerd
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-fira-sans
      - ttf-firacode-nerd
      - ttf-hack-nerd
      - ttf-iosevka-nerd
      - ttf-iosevkaterm-nerd
      - ttf-jetbrains-mono
      - ttf-nerd-fonts-symbols-mono
    state: present
- name: Install AUR font packages
  ansible.builtin.include_role:
    name: aur_build
  vars:
    aur_packages:
      - ttf-ms-fonts # wingdings
      - ttf-croscore # MS Office Fonts
      - ttf-vista-fonts # MS Office Fonts
- name: Clear font cache
  ansible.builtin.command: fc-cache -f -v
  changed_when: false
