- name: Install Python packages
  become: true
  community.general.pacman:
    name:
      - python
      - python-pip
      - python-pipx
      - python-virtualenv
    state: present

# - name: Install Python versions from AUR
#   kewlfft.aur.aur:
#     name: "{{ item }}"
#     state: present
#   loop:
#     - python38
#     - python39
#     - python310
#     - python311
#     - python312
