- name: Install fingerprint packages
  become: true
  community.general.pacman:
    name:
      - fprintd
    state: present
- name: Enable fprintd service
  become: true
  ansible.builtin.systemd:
    name: fprintd.service
    enabled: true
  when: ansible_facts['virtualization_type'] != "docker"
