- name: Install litra-rs - Logitech Light controller (https://github.com/timrogers/litra-rs)
  ansible.builtin.shell: cargo install litra-rs
  args:
    executable: /bin/bash
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/litra-rs"
