- name: Install CLI tools
  become: true
  community.general.pacman:
    name:
      - jq
      - yq
      - tldr
      - which
      - fastfetch
      - yazi
      - codespell
      - tree
    state: present
- name: Install Rust-based CLI tools
  ansible.builtin.shell: cargo install {{ item }}
  args:
    executable: /bin/bash
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/{{ item }}"
  loop:
    - exa
    - bat
    - ripgrep
    - fd-find
    - procs
    - bottom
    - dysk
- name: Ensure go is installed
  ansible.builtin.import_tasks: tasks/development/golang.yml
- name: Install lazygit
  ansible.builtin.shell: go install github.com/jesseduffield/lazygit@latest
  args:
    executable: /bin/bash
    creates: "{{ ansible_facts.env.HOME }}/go/bin/lazygit"
- name: Install lazydocker
  ansible.builtin.shell: go install github.com/jesseduffield/lazydocker@latest
  args:
    executable: /bin/bash
    creates: "{{ ansible_facts.env.HOME }}/go/bin/lazydocker"
- name: Install Python tools via pipx
  ansible.builtin.include_role:
    name: pipx_install
  vars:
    package_name: "{{ item }}"
  loop:
    - gdown
    - yt-dlp
