---
# Install all pipx packages

- name: Ensure pipx path
  command: pipx ensurepath
  changed_when: false

- name: Install pipx packages
  command: "pipx install {{ item }}"
  loop: "{{ pipx_packages }}"
  register: pipx_result
  changed_when: "'installed package' in pipx_result.stdout"
  failed_when: false
  when: pipx_packages | length > 0
