---
# Enable systemd services

- name: Enable systemd services
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ systemd_services }}"
  failed_when: false
  when: systemd_services | length > 0
