---
pacman_packages:
  # base
  - git
  - vim
  - vi
  - less
  - curl
  - wget
  - unzip
  - base-devel
  # alacritty
  - alacritty
  # bluetooth
  - bluez
  - bluez-utils
  - bluetui
  # cmake
  - cmake
  # cpp
  - gmock
  - gtest
  - cppcheck
  - boost
  - valgrind
  - perf
  - bear
  - clang
  - mingw-w64-gcc
  # dart
  - dart
  # desktop
  - gnome
  - gnome-extra
  - gnome-tweaks
  - gnome-shell-extensions
  - baobab
  - file-roller
  - sushi
  - gnome-calculator
  - gnome-system-monitor
  - gnome-disk-utility
  - gnome-font-viewer
  - simple-scan
  - evince
  - gst-libav
  - gst-plugins-good
  - gst-plugins-bad
  - gst-plugins-ugly
  - networkmanager
  - cups
  - cups-pdf
  - hyprland
  - cpio
  - glaze
  - hyprland-protocols
  - uwsm
  # dev-tools
  - ffmpeg
  - pandoc
  - pdfarranger
  - qt6-base
  - ninja
  - meson
  # docker
  - docker
  - docker-compose
  - docker-buildx
  # dotnet
  - dotnet-sdk
  # emacs
  - emacs
  # filesystem
  - exfat-utils
  - ntfs-3g
  # fingerprint
  - fprintd
  # flatpak
  - flatpak
  # font
  - fontconfig
  - ttf-jetbrains-mono-nerd
  - ttf-dejavu
  - ttf-nerd-fonts-symbols
  - ttf-ubuntu-font-family
  - noto-fonts
  - noto-fonts-emoji
  - noto-fonts-cjk
  - ttf-liberation
  # git
  - git-lfs
  # golang
  - go
  # haskell
  - stack
  - cabal-install
  # java
  - maven
  - jdk8-openjdk
  - jdk21-openjdk
  - zip
  # keyring
  - gnome-keyring
  - gcr
  - seahorse
  # latex
  - texlive-core
  - texlive-bin
  - texlive-latexextra
  - texlive-science
  - texlive-fontsextra
  - texlive-pictures
  - texlive-pstricks
  - texlive-mathscience
  - texlive-lang
  - plantuml
  # lua
  - luarocks
  # lvim
  - python-pynvim
  - xclip
  - ruby
  - r
  - php
  - llvm
  - lldb
  - hunspell
  # misc
  - libreoffice
  - gimp
  - qt5-base
  - obs-studio
  - pdftk
  - bison
  - xournalpp
  - okular
  - krita
  - vlc
  - drawio-desktop
  - flameshot
  - flex
  # neovim
  - gettext
  # node
  - nodejs
  - npm
  # nvidia
  - nvidia
  - nvidia-utils
  - nvidia-settings
  - cuda
  # ocaml
  - opam
  # ollama
  - ollama-cuda
  # opencv
  - opencv
  - python-opencv
  - hdf5
  - vtk
  - glew
  # python
  - python
  - python-pip
  - python-pipx
  - python-virtualenv
  # racket
  - racket
  - graphviz
  # rust
  - rust
  # terminal
  - zsh
  # virtualbox
  - virtualbox
  - virtualbox-host-modules-arch

aur_packages: # yay
  # bazel
  - bazel
  # chrome
  - google-chrome
  # dell-laptop
  - dell-powermanager-git
  # desktop
  - yaru-theme
  - better-control-git
  # flutter
  - flutter
  # font
  - nerd-fonts-jetbrains-mono
  # haskell
  - ghcup-hs-bin
  # misc
  - postman-bin
  - pdfarranger
  - amberol
  - pympress
  # nvidia
  - nvidia-container-toolkit
  # ollama
  - ollama
  # python
  - python38
  - python39
  - python310
  - python311
  - python312
  # snap
  - snapd
  # terminal
  - oh-my-zsh-git
  # unity
  - unityhub
  # vpn
  - openconnect
  - networkmanager-openconnect
  # vscode
  - visual-studio-code-bin
  # webots
  - webots-bin

pipx_packages:
  # gdrive
  - gdown
  # lvim
  - neovim
  - bandit
  - flake8
  # misc
  - screenpen
  # python
  - pre-commit
  - jupyterlab
  - notebook
  # youtube
  - yt-dlp

npm_packages: []

cargo_packages:
  # misc
  - exa
  - bat
  - ripgrep
  - fd-find
  - procs
  - bottom
  - dysk
  # rust
  - cargo-update

go_packages:
  # docker
  - github.com/jesseduffield/lazydocker@latest
  # golang
  - github.com/jesseduffield/lazygit@latest

flatpak_packages:
  - com.discordapp.Discord
  - org.mozilla.Thunderbird
  - io.missioncenter.MissionCenter
  - net.ankiweb.Anki

systemd_services:
  - bluetooth
  # desktop
  - gdm
  - NetworkManager
  - cups
  - docker
  - fprintd
  - nvidia-persistenced
  - snapd.socket

git_user_name: "Anton Kesy"
git_user_email: "antonkesy@gmail.com"
git_editor: "lvim"
