---
- name: Install Homebrew dependencies
  become: true
  community.general.pacman:
    name:
      - base-devel
      - procps-ng
      - curl
      - file
      - git
      - ruby-erb
    state: present

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: homebrew_check

- name: Install Homebrew
  become: false
  environment:
    NONINTERACTIVE: "1"
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew
