---
- name: Install Lua packages
  become: true
  community.general.pacman:
    name:
      - luarocks
    state: present

- name: Install luacheck
  become: true
  ansible.builtin.command: luarocks install luacheck
  changed_when: false
