---
- name: Install Ollama from AUR
  ansible.builtin.include_role:
    name: aur_build
  vars:
    package_name: ollama

- name: Install Ollama CUDA support
  become: true
  community.general.pacman:
    name:
      - ollama-cuda
    state: present
