- name: Install Neovim build dependencies
  become: true
  community.general.pacman:
    name:
      - ninja
      - gettext
      - cmake
      - unzip
      - curl
      - base-devel
    state: present
- name: Create neovim build directory
  ansible.builtin.file:
    path: "{{ playbook_dir | dirname }}/build/neovim"
    state: directory
    mode: "0755"
- name: Clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ playbook_dir | dirname }}/build/neovim"
    version: v0.11.5
    depth: 1
- name: Check if neovim binary exists
  ansible.builtin.stat:
    path: "{{ playbook_dir | dirname }}/build/neovim/build/bin/nvim"
- name: Build neovim
  become: true
  community.general.make:
    chdir: "{{ playbook_dir | dirname }}/build/neovim"
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
- name: Install neovim
  become: true
  community.general.make:
    chdir: "{{ playbook_dir | dirname }}/build/neovim"
    target: install
