- name: Install C++ development tools (Pacman)
  become: true
  community.general.pacman:
    name:
      - base-devel
      - gmock
      - gtest
      - cppcheck
      - boost
      - valgrind
      - perf
      - bear
      - clang
      - meson
      - llvm
      - mingw-w64-gcc
    state: present
