- name: Install development tools
  become: true
  community.general.pacman:
    name:
      - ffmpeg
      - qt6-base
      - ninja
      - meson
      - bazel
      - cmake
      - arduino-cli
      - bison
      - flex
    state: present
- name: Install Python tools via pipx
  ansible.builtin.include_role:
    name: pipx_install
  vars:
    package_name: "{{ item }}"
  loop:
    - pre-commit
    - jupyterlab
    - notebook
