---
- name: Install development tools
  become: true
  community.general.pacman:
    name:
      - ffmpeg
      - qt6-base
      - ninja
      - meson
      - bazel
      - cmake
      - arduino-cli
      - bison
      - flex
    state: present
