- name: Install development tools & Libs
  become: true
  community.general.pacman:
    name:
      - ffmpeg
      - qt6-base
      - ninja
      - meson
      - bazel
      - cmake
      - arduino-cli
      - bison
      - flex
      - eigen
      - spglib
      - jkqtplotter
      - openbabel
      - libarchive
      - msgpack-c
      - glew
    state: present
- name: Install Python tools via pipx
  ansible.builtin.include_role:
    name: pipx_install
  vars:
    package_name: "{{ item }}"
  loop:
    - pre-commit
    - jupyterlab
    - notebook
- name: Install Libs development tools (AUR)
  ansible.builtin.include_role:
    name: aur_build
  vars:
    aur_packages:
      - mmtf-cpp
      - libmsym
