- name: Install Rust packages
  become: true
  community.general.pacman:
    name:
      - rust
      - libgit2
      - libcurl-compat
      - libssh2
      - openssl
      - pkgconf
    state: present
- name: Install cargo-update
  ansible.builtin.shell: cargo install cargo-update
  args:
    executable: /bin/bash
    creates: "{{ ansible_facts.env.HOME }}/.cargo/bin/cargo-install-update"
