- name: Install Rust packages
  become: true
  community.general.pacman:
    name:
      - rust
      - libgit2
      - libcurl-compat
      - libssh2
      - openssl
      - pkgconf
    state: present
- name: Install cargo-update
  ansible.builtin.include_role:
    name: cargo_install
  vars:
    package_name: "cargo-update"
    binary_name: "cargo-install-update"
