import = [ "~/.config/alacritty/themes/themes/iterm.toml" ]
# import = [ "~/.config/alacritty/themes/themes/github_dark_colorblind.toml" ]

# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
[env]
TERM="xterm-256color"

[window]
decorations = "Full"
startup_mode = "Maximized"

[scrolling]
history = 50000 

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
# normal = { family = "Monaspace Argon", style = "Regular" }
size = 12

# [bell]
# duration = 5

[terminal]
osc52 = "CopyPaste"

[shell]
program = "tmux"
args = ["new", "-A", "-s", "main"]

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "F11", mods = "Alt", action = "ToggleFullscreen" },
]
