---
# Development tools

- name: Install dev tools
  become: true
  pacman:
    name:
      - git
      - ffmpeg
      - pandoc
      - pdfarranger
      - curl
      - qt6-base
      - base-devel
      - vim
      - vi
      - less
      - exfat-utils
      - ntfs-3g
    state: present
