---
# Git packages and configuration
git:
  pacman_packages:
    - git
    - git-lfs
  aur_packages: []
  pipx_packages: []
  npm_packages: []
  cargo_packages: []
  flatpak_packages: []
  systemd_services: []

# GIT CONFIGURATION
git_user_name: "Anton Kesy"
git_user_email: "antonkesy@gmail.com"
git_editor: "lvim"
