---
lvim:
  pacman_packages:
    - python-pynvim
    - xclip
    - ruby
    - r
    - php
    - llvm
    - lldb
    - hunspell
  aur_packages: []
  pipx_packages:
    - neovim
    - bandit
    - flake8
  cargo_packages: []
  flatpak_packages: []
  systemd_services: []
