---
python:
  pacman_packages:
    - python
    - python-pip
    - python-pipx
    - python-virtualenv
  aur_packages:
    - python38
    - python39
    - python310
    - python311
    - python312
  pipx_packages:
    # Git hooks
    - pre-commit
    # Jupyter
    - jupyterlab
    - notebook
  npm_packages: []
  cargo_packages: []
  flatpak_packages: []
  systemd_services: []
